class locators:

    str_flight_button = "//a[@id='flights']"
    str_one_way_button = "//div[contains(text(),'One way')]"
    str_dismiss_sign_in = "//button[@aria-label='Dismiss sign in information.']"
    str_from_field_click = "//button[@data-ui-sr='location_input_from_0']"
    str_airport_city_field = "//input[@placeholder='Airport or city']"
    str_remove_loc = "//span[@class='Icon-module__root___0jUKs css-lyj9ft Icon-module__root--size-small___AvlR0']//*[name()='svg']"
    str_delhi_airport_select = "//b[text()='DEL']"
    str_bangalore_airport_select = "//b[text()='BLR']"
    str_to_field_click = "//button[@aria-describedby='location_input_to_0_error']"
    str_date_picker = "//span[@aria-label='<<text_replace>>']"
    str_click_departure_date_chooser = "//button[@placeholder='Choose departure date']"
    str_search_button = "//span[text()='Search']"
    str_cheapest_tab = "//button[@data-testid='search_tabs_CHEAPEST']"
    str_first_chepest_flight = "//button[@aria-describedby='flight-card-0']"
    str_final_select = "//span[normalize-space()='Select']"
    str_popup = "//div[contains(text(),'Look out for flexible ticket options...')]"
